2019-09-02 15:50:06.184 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-02 15:50:06.196 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-02 15:50:06.202 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-02 15:50:06.206 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-02 15:50:06.206 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-02 15:50:06.217 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-02 15:50:06.217 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-02 15:50:06.221 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-02 15:50:06.227 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-02 15:50:06.227 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-02 15:50:06.232 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-02 15:50:06.247 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-02 15:50:06.248 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-02 15:50:06.250 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-02 15:50:06.251 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-02 15:50:06.257 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-02 15:50:07.000 [warning] <0.636.0> lager_error_logger_h dropped 376 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-02 15:50:08.956 [error] <0.958.0> ** Task <0.958.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-02 15:50:09.003 [error] <0.958.0> CRASH REPORT Process <0.958.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-02 15:50:09.004 [error] <0.825.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.958.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-02 15:50:11.405 [error] <0.411.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 gen_server tzdata_release_updater terminated with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-02 15:50:11.420 [error] <0.411.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-02 15:50:11.421 [error] <0.405.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 Supervisor {<0.405.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.411.0> exit with reason no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73 in context child_terminated
2019-09-02 16:57:43.859 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-02 16:57:43.869 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-02 16:57:43.875 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-02 16:57:43.879 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-02 16:57:43.879 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-02 16:57:43.889 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-02 16:57:43.889 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-02 16:57:43.892 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-02 16:57:43.900 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-02 16:57:43.900 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-02 16:57:43.907 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-02 16:57:43.921 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-02 16:57:43.923 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-02 16:57:43.925 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-02 16:57:43.926 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-02 16:57:43.931 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-02 16:57:44.000 [warning] <0.582.0> lager_error_logger_h dropped 99 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-02 16:57:44.025 [info] <0.43.0> Application swarm started on node nonode@nohost
2019-09-02 16:57:44.037 [info] <0.43.0> Application quantum started on node nonode@nohost
2019-09-02 17:17:28.255 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-02 17:17:28.266 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-02 17:17:28.272 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-02 17:17:28.276 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-02 17:17:28.277 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-02 17:17:28.287 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-02 17:17:28.287 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-02 17:17:28.291 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-02 17:17:28.298 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-02 17:17:28.298 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-02 17:17:28.304 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-02 17:17:28.320 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-02 17:17:28.322 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-02 17:17:28.323 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-02 17:17:28.324 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-02 17:17:28.329 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-02 17:17:28.999 [warning] <0.572.0> lager_error_logger_h dropped 376 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-02 18:17:06.595 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-02 18:17:06.606 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-02 18:17:06.612 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-02 18:17:06.616 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-02 18:17:06.616 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-02 18:17:06.630 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-02 18:17:06.630 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-02 18:17:06.634 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-02 18:17:06.642 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-02 18:17:06.642 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-02 18:17:06.647 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-02 18:17:06.667 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-02 18:17:06.669 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-02 18:17:06.670 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-02 18:17:06.671 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-02 18:17:06.677 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-02 18:17:07.001 [warning] <0.577.0> lager_error_logger_h dropped 244 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-02 18:17:07.027 [info] <0.43.0> Application erlexec started on node nonode@nohost
2019-09-02 18:17:07.027 [info] <0.43.0> Application exexec started on node nonode@nohost
2019-09-02 18:17:07.034 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-09-02 18:17:07.040 [info] <0.43.0> Application poison started on node nonode@nohost
2019-09-02 18:17:07.052 [info] <0.43.0> Application base64url started on node nonode@nohost
2019-09-02 18:17:07.140 [info] <0.43.0> Application jose started on node nonode@nohost
2019-09-02 18:17:07.141 [info] <0.43.0> Application joken started on node nonode@nohost
2019-09-02 18:17:07.161 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-09-05 15:14:50.144 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-05 15:14:50.160 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-05 15:14:50.166 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-05 15:14:50.169 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-05 15:14:50.169 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-05 15:14:50.182 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-05 15:14:50.182 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-05 15:14:50.185 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-05 15:14:50.192 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-05 15:14:50.192 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-05 15:14:50.198 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-05 15:14:50.221 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-05 15:14:50.222 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-05 15:14:50.224 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-05 15:14:50.225 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-05 15:14:50.230 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-05 15:14:51.000 [warning] <0.658.0> lager_error_logger_h dropped 376 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-05 15:14:52.872 [error] <0.980.0> ** Task <0.980.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-05 15:14:52.908 [error] <0.980.0> CRASH REPORT Process <0.980.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-05 15:14:52.909 [error] <0.847.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.980.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-05 15:19:21.101 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-05 15:19:21.114 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-05 15:19:21.120 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-05 15:19:21.123 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-05 15:19:21.124 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-05 15:19:21.134 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-05 15:19:21.134 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-05 15:19:21.138 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-05 15:19:21.144 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-05 15:19:21.144 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-05 15:19:21.148 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-05 15:19:21.164 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-05 15:19:21.166 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-05 15:19:21.167 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-05 15:19:21.168 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-05 15:19:21.173 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-05 15:19:22.000 [warning] <0.662.0> lager_error_logger_h dropped 376 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-06 11:09:19.976 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-06 11:09:19.987 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-06 11:09:19.993 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-06 11:09:19.996 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-06 11:09:19.996 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-06 11:09:20.009 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-06 11:09:20.009 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-06 11:09:20.012 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-06 11:09:20.019 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-06 11:09:20.019 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-06 11:09:20.024 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-06 11:09:20.040 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-06 11:09:20.041 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-06 11:09:20.043 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-06 11:09:20.044 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-06 11:09:20.049 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-06 11:09:21.000 [warning] <0.605.0> lager_error_logger_h dropped 376 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-06 11:09:22.709 [error] <0.927.0> ** Task <0.927.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-06 11:09:22.798 [error] <0.927.0> CRASH REPORT Process <0.927.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-06 11:09:22.800 [error] <0.794.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.927.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-06 11:09:25.309 [error] <0.380.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 gen_server tzdata_release_updater terminated with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-06 11:09:25.317 [error] <0.380.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-06 11:09:25.318 [error] <0.374.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 Supervisor {<0.374.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.380.0> exit with reason no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73 in context child_terminated
2019-09-12 14:40:56.275 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-12 14:40:56.286 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-12 14:40:56.292 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-12 14:40:56.296 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-12 14:40:56.296 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-12 14:40:56.308 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-12 14:40:56.308 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-12 14:40:56.312 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-12 14:40:56.319 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-12 14:40:56.319 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-12 14:40:56.324 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-12 14:40:56.349 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-12 14:40:56.350 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-12 14:40:56.352 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-12 14:40:56.353 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-12 14:40:56.357 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-12 14:40:57.000 [warning] <0.605.0> lager_error_logger_h dropped 376 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-12 14:41:28.433 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-12 14:41:28.445 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-12 14:41:28.451 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-12 14:41:28.454 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-12 14:41:28.455 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-12 14:41:28.467 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-12 14:41:28.468 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-12 14:41:28.471 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-12 14:41:28.477 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-12 14:41:28.478 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-12 14:41:28.486 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-12 14:41:28.508 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-12 14:41:28.510 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-12 14:41:28.512 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-12 14:41:28.513 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-12 14:41:28.522 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-12 14:41:29.000 [warning] <0.606.0> lager_error_logger_h dropped 250 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-12 14:41:29.007 [info] <0.43.0> Application poison started on node nonode@nohost
2019-09-12 14:41:29.022 [info] <0.43.0> Application base64url started on node nonode@nohost
2019-09-12 14:41:29.129 [info] <0.43.0> Application jose started on node nonode@nohost
2019-09-12 14:41:29.129 [info] <0.43.0> Application joken started on node nonode@nohost
2019-09-12 14:41:29.146 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-09-12 14:41:30.001 [warning] <0.606.0> lager_error_logger_h dropped 79 messages in the last second that exceeded the limit of 50 messages/sec
2019-09-12 14:41:41.065 [info] <0.43.0> Application lager started on node nonode@nohost
2019-09-12 14:41:41.075 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-09-12 14:41:41.081 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-09-12 14:41:41.085 [info] <0.43.0> Application recon started on node nonode@nohost
2019-09-12 14:41:41.085 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-09-12 14:41:41.095 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-09-12 14:41:41.095 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-09-12 14:41:41.099 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-09-12 14:41:41.106 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-09-12 14:41:41.106 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-09-12 14:41:41.111 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-09-12 14:41:41.125 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-09-12 14:41:41.129 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-09-12 14:41:41.131 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-09-12 14:41:41.132 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-09-12 14:41:41.136 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-09-12 14:41:42.000 [warning] <0.571.0> lager_error_logger_h dropped 378 messages in the last second that exceeded the limit of 50 messages/sec
2019-10-16 18:17:58.460 [info] <0.43.0> Application lager started on node nonode@nohost
2019-10-16 18:17:58.469 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-10-16 18:17:58.477 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-10-16 18:17:58.483 [info] <0.43.0> Application recon started on node nonode@nohost
2019-10-16 18:17:58.483 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-10-16 18:17:58.583 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-10-16 18:17:58.584 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-10-16 18:17:58.615 [info] <0.43.0> Application httpoison started on node nonode@nohost
2019-10-16 18:17:58.636 [info] <0.43.0> Application comeonin started on node nonode@nohost
2019-10-16 18:17:58.636 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2019-10-16 18:17:58.641 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-10-16 18:17:58.661 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-10-16 18:17:58.663 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-10-16 18:17:58.664 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-10-16 18:17:58.665 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-10-16 18:17:58.671 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-10-16 18:17:59.000 [warning] <0.669.0> lager_error_logger_h dropped 230 messages in the last second that exceeded the limit of 50 messages/sec
2019-10-16 18:17:59.037 [info] <0.43.0> Application archive started on node nonode@nohost
2019-10-16 18:17:59.058 [info] <0.43.0> Application ex_json_schema started on node nonode@nohost
2019-10-16 18:17:59.084 [info] <0.43.0> Application hpack started on node nonode@nohost
2019-10-16 18:17:59.093 [info] <0.43.0> Application kadabra started on node nonode@nohost
2019-10-16 18:17:59.199 [info] <0.43.0> Application erlexec started on node nonode@nohost
2019-10-16 18:17:59.199 [info] <0.43.0> Application exexec started on node nonode@nohost
2019-10-16 18:17:59.206 [error] <0.1008.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1008.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-10-16 18:17:59.206 [error] <0.1009.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1009.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-10-16 18:17:59.212 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-10-16 18:17:59.221 [info] <0.43.0> Application poison started on node nonode@nohost
2019-10-16 18:17:59.232 [info] <0.43.0> Application base64url started on node nonode@nohost
2019-10-16 18:17:59.322 [info] <0.43.0> Application jose started on node nonode@nohost
2019-10-16 18:17:59.322 [info] <0.43.0> Application joken started on node nonode@nohost
2019-10-16 18:17:59.340 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-10-16 18:18:00.000 [warning] <0.669.0> lager_error_logger_h dropped 99 messages in the last second that exceeded the limit of 50 messages/sec
2019-10-16 18:18:11.013 [error] <0.1153.0> CRASH REPORT Process <0.1153.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.179 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,1,<0.1153.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encodin...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-10-16 18:18:11.488 [error] <0.1156.0> CRASH REPORT Process <0.1156.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.497 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,2,<0.1156.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-10-16 18:18:11.666 [error] <0.1159.0> CRASH REPORT Process <0.1159.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:40...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.678 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,3,<0.1159.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 15:42:51.787 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 15:42:51.801 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 15:42:51.808 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 15:42:51.821 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 15:42:51.825 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 15:42:51.825 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 15:42:51.839 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 15:42:51.839 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 15:42:51.847 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 15:42:51.854 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 15:42:51.857 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 15:42:51.864 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 15:42:51.878 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 15:42:51.880 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 15:42:51.881 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 15:42:51.883 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 15:42:51.886 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 15:42:51.999 [warning] <0.730.0> lager_error_logger_h dropped 468 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 15:42:52.004 [info] <0.43.0> Application gen_state_machine started on node nonode@nohost
2019-11-17 15:42:52.010 [info] <0.43.0> Application libring started on node nonode@nohost
2019-11-17 15:42:52.044 [info] <0.43.0> Application swarm started on node nonode@nohost
2019-11-17 15:42:52.058 [info] <0.43.0> Application quantum started on node nonode@nohost
2019-11-17 15:42:53.000 [warning] <0.730.0> lager_error_logger_h dropped 224 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 15:46:07.222 [error] <0.1609.0> CRASH REPORT Process <0.1609.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',action,2,[{file,"lib/domoapi_intercom_web/controllers/intercom_controller.ex"},{...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 15:46:07.251 [error] <0.732.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.1608.0>,1,<0.1609.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',...},...]},...},...]},...}}
2019-11-17 15:52:28.934 [error] <0.1634.0> CRASH REPORT Process <0.1634.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',action,2,[{file,"lib/domoapi_intercom_web/controllers/intercom_controller.ex"},{...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 15:52:28.940 [error] <0.732.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.1633.0>,1,<0.1634.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',...},...]},...},...]},...}}
2019-11-17 15:53:22.119 [error] <0.1642.0> CRASH REPORT Process <0.1642.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',action,2,[{file,"lib/domoapi_intercom_web/controllers/intercom_controller.ex"},{...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 15:53:22.124 [error] <0.732.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.1641.0>,1,<0.1642.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',...},...]},...},...]},...}}
2019-11-17 15:54:36.893 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 15:54:36.906 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 15:54:36.912 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 15:54:36.924 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 15:54:36.928 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 15:54:36.928 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 15:54:36.938 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 15:54:36.939 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 15:54:36.946 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 15:54:36.952 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 15:54:36.954 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 15:54:36.961 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 15:54:36.977 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 15:54:36.979 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 15:54:36.980 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 15:54:36.981 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 15:54:36.984 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 15:54:38.000 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 17:07:43.560 [error] <0.1811.0> CRASH REPORT Process <0.1811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 17:07:43.599 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1810.0>,1,<0.1811.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-enc...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-17 17:10:20.916 [error] <0.1846.0> CRASH REPORT Process <0.1846.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 200,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"bearer">> => <<"SFMyNTY.g3QAAAABbQAAABZndWFyZGlhbl9kZWZhdWx0X3Rva2VubQAAAYZleUpoYkdjaU9pSklVelV4TWlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaGRXUWlPaUprYjIxdl...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 17:10:20.924 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1845.0>,1,<0.1846.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 200,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"bearer">> => <<"SFMyNTY.g3QAAAABbQAAABZndWFyZGlhbl9kZWZhdWx0...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 18:36:44.815 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 18:36:44.851 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 18:36:44.860 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 18:36:44.890 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 18:36:44.897 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 18:36:44.897 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 18:36:44.909 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 18:36:44.910 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 18:36:44.917 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 18:36:44.922 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 18:36:44.925 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 18:36:44.932 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 18:36:44.946 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 18:36:44.948 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 18:36:44.949 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 18:36:44.951 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 18:36:44.953 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 18:36:46.000 [warning] <0.443.0> lager_error_logger_h dropped 742 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 18:40:07.944 [error] <0.1309.0> CRASH REPORT Process <0.1309.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 58,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"upgrade">>,<<"c...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:40:07.985 [error] <0.445.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1308.0>,1,<0.1309.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 58,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 18:44:36.020 [error] <0.1328.0> CRASH REPORT Process <0.1328.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"deflate, gzip">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"user-api.domoface.ru">>,<<"user-agent">> => <<"Mozilla/...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:44:36.026 [error] <0.445.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1327.0>,1,<0.1328.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"deflate, gzip">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 18:53:04.670 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 18:53:04.681 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 18:53:04.688 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 18:53:04.699 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 18:53:04.703 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 18:53:04.703 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 18:53:04.714 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 18:53:04.714 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 18:53:04.722 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 18:53:04.728 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 18:53:04.731 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 18:53:04.738 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 18:53:04.752 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 18:53:04.753 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 18:53:04.754 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 18:53:04.755 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 18:53:04.758 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 18:53:05.000 [warning] <0.453.0> lager_error_logger_h dropped 601 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 18:53:05.015 [info] <0.43.0> Application archive started on node nonode@nohost
2019-11-17 18:53:05.030 [info] <0.43.0> Application ex_json_schema started on node nonode@nohost
2019-11-17 18:53:05.055 [info] <0.43.0> Application hpack started on node nonode@nohost
2019-11-17 18:53:05.062 [info] <0.43.0> Application kadabra started on node nonode@nohost
2019-11-17 18:53:05.071 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-11-17 18:53:05.086 [info] <0.43.0> Application poison started on node nonode@nohost
2019-11-17 18:53:05.091 [info] <0.43.0> Application joken started on node nonode@nohost
2019-11-17 18:53:05.114 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-11-17 18:53:06.000 [warning] <0.453.0> lager_error_logger_h dropped 91 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 18:53:27.464 [error] <0.1316.0> CRASH REPORT Process <0.1316.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => {ok,<<123,34,99,97,110,100,105,100,97,116,101,34,58,34,65,117,101,32,208,178,209,129,209,143,32,209,133,209,131,208,185,208,189,209,143,32,208,178,208,190,209,128,32,208,178,32,208,183,208,176,208,186,208,190,208,189,208,181,32,208,180,208,176,34,125>>}},[{hackney_request,handle_body,4,[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_request.erl"},{line,318}]},{hackney_request,perform,2,[{file,"/home/..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:53:27.497 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1315.0>,1,<0.1316.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => {ok,<<123,34,99,97,110,100,105,100,97,116,101,34,58,34,65,117,101,32,208,178,209,129,209,143,32,209,133,209,131,208,185,208,189,209,143,32,208,178,208,190,209,128,32,208,178,32,208,183,208,176,208,186,208,190,208,189,208,181,32,208,180,208,176,34,125>>}},[{hackney_request,handle_body,4,[{file,"/home/ubuntu/domoapi/domoapi/deps/h..."},...]},...]},...},...]},...}}
2019-11-17 18:54:22.729 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 18:54:22.741 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 18:54:22.748 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 18:54:22.758 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 18:54:22.762 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 18:54:22.762 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 18:54:22.774 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 18:54:22.774 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 18:54:22.782 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 18:54:22.787 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 18:54:22.790 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 18:54:22.797 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 18:54:22.812 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 18:54:22.813 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 18:54:22.815 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 18:54:22.816 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 18:54:22.819 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 18:54:22.999 [warning] <0.453.0> lager_error_logger_h dropped 474 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 18:54:23.008 [info] <0.43.0> Application quantum started on node nonode@nohost
2019-11-17 18:54:24.000 [warning] <0.453.0> lager_error_logger_h dropped 218 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 18:58:36.200 [error] <0.1389.0> CRASH REPORT Process <0.1389.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"199">>,<<"content-type">> => <<"application/x-www-form-urlencoded; charset=UTF-8">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:58:36.201 [error] <0.1387.0> CRASH REPORT Process <0.1387.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"14">>,<<"content-type">> => <<"application/x-www-form-urlencoded; charset=UTF-8">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:58:36.201 [error] <0.1391.0> CRASH REPORT Process <0.1391.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"232">>,<<"content-type">> => <<"application/x-www-form-urlencoded; charset=UTF-8">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:58:36.263 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1390.0>,1,<0.1391.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"23...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 19:13:54.445 [error] <0.1722.0> CRASH REPORT Process <0.1722.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:13:54.456 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1721.0>,1,<0.1722.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:23.624 [error] <0.1800.0> CRASH REPORT Process <0.1800.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:23.635 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1799.0>,1,<0.1800.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:23.722 [error] <0.1803.0> CRASH REPORT Process <0.1803.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:23.733 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1802.0>,1,<0.1803.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:24.052 [error] <0.1808.0> CRASH REPORT Process <0.1808.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:24.061 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1807.0>,1,<0.1808.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:24.090 [error] <0.1811.0> CRASH REPORT Process <0.1811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:24.100 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1810.0>,1,<0.1811.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:17:27.286 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:17:27.297 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:17:27.303 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:17:27.313 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:17:27.318 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:17:27.318 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:17:27.331 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:17:27.331 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:17:27.339 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:17:27.345 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:17:27.348 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:17:27.355 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:17:27.369 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:17:27.371 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:17:27.372 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:17:27.373 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:17:27.376 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:17:28.000 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:17:49.981 [error] <0.1334.0> CRASH REPORT Process <0.1334.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:49.981 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:49.982 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:49.982 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:50.021 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1331.0>,1,<0.1334.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:20:26.679 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:20:26.690 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:20:26.696 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:20:26.706 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:20:26.710 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:20:26.710 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:20:26.721 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:20:26.721 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:20:26.729 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:20:26.735 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:20:26.737 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:20:26.745 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:20:26.759 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:20:26.761 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:20:26.762 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:20:26.763 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:20:26.766 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:20:26.999 [warning] <0.454.0> lager_error_logger_h dropped 600 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:20:27.024 [info] <0.43.0> Application archive started on node nonode@nohost
2019-11-17 19:20:27.038 [info] <0.43.0> Application ex_json_schema started on node nonode@nohost
2019-11-17 19:20:27.056 [info] <0.43.0> Application hpack started on node nonode@nohost
2019-11-17 19:20:27.066 [info] <0.43.0> Application kadabra started on node nonode@nohost
2019-11-17 19:20:27.074 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-11-17 19:20:27.088 [info] <0.43.0> Application poison started on node nonode@nohost
2019-11-17 19:20:27.093 [info] <0.43.0> Application joken started on node nonode@nohost
2019-11-17 19:20:27.116 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-11-17 19:20:28.000 [warning] <0.454.0> lager_error_logger_h dropped 92 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:21:26.823 [error] <0.1378.0> CRASH REPORT Process <0.1378.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.823 [error] <0.1369.0> CRASH REPORT Process <0.1369.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.824 [error] <0.1376.0> CRASH REPORT Process <0.1376.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.825 [error] <0.1373.0> CRASH REPORT Process <0.1373.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.856 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1377.0>,1,<0.1378.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],...}}}}],...},...]},...},...]},...}}
2019-11-17 19:26:48.655 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:26:48.666 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:26:48.672 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:26:48.683 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:26:48.686 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:26:48.687 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:26:48.698 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:26:48.698 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:26:48.705 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:26:48.711 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:26:48.713 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:26:48.720 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:26:48.735 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:26:48.737 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:26:48.739 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:26:48.740 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:26:48.743 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:26:49.001 [warning] <0.453.0> lager_error_logger_h dropped 602 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:26:49.002 [info] <0.43.0> Application archive started on node nonode@nohost
2019-11-17 19:26:49.016 [info] <0.43.0> Application ex_json_schema started on node nonode@nohost
2019-11-17 19:26:49.034 [info] <0.43.0> Application hpack started on node nonode@nohost
2019-11-17 19:26:49.042 [info] <0.43.0> Application kadabra started on node nonode@nohost
2019-11-17 19:26:49.049 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-11-17 19:26:49.069 [info] <0.43.0> Application poison started on node nonode@nohost
2019-11-17 19:26:49.073 [info] <0.43.0> Application joken started on node nonode@nohost
2019-11-17 19:26:49.100 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-11-17 19:26:50.000 [warning] <0.453.0> lager_error_logger_h dropped 90 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:27:10.504 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.504 [error] <0.1337.0> CRASH REPORT Process <0.1337.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.504 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.505 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.550 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1338.0>,1,<0.1339.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:30:00.587 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:30:00.597 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:30:00.603 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:30:00.612 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:30:00.616 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:30:00.617 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:30:00.628 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:30:00.628 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:30:00.635 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:30:00.641 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:30:00.643 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:30:00.651 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:30:00.667 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:30:00.669 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:30:00.670 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:30:00.671 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:30:00.674 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:30:00.999 [warning] <0.454.0> lager_error_logger_h dropped 615 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:30:01.001 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-11-17 19:30:01.013 [info] <0.43.0> Application poison started on node nonode@nohost
2019-11-17 19:30:01.017 [info] <0.43.0> Application joken started on node nonode@nohost
2019-11-17 19:30:01.042 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-11-17 19:30:02.000 [warning] <0.454.0> lager_error_logger_h dropped 77 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:30:15.582 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:30:15.582 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:30:15.582 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:30:15.624 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1339.0>,1,<0.1340.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:34:54.083 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:34:54.094 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:34:54.100 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:34:54.110 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:34:54.114 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:34:54.114 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:34:54.124 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:34:54.125 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:34:54.132 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:34:54.137 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:34:54.140 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:34:54.146 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:34:54.159 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:34:54.160 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:34:54.162 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:34:54.163 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:34:54.165 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:34:54.219 [error] <0.520.0> Failed to start Ranch listener 'Elixir.DomoapiUserWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,9080}]) for reason eaddrinuse (address already in use)
2019-11-17 19:34:54.250 [error] <0.518.0> Supervisor {<0.518.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.DomoapiUserWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2019-11-17 19:34:54.250 [error] <0.520.0> CRASH REPORT Process <0.520.0> with 0 neighbours exited with reason: {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2019-11-17 19:34:54.251 [error] <0.499.0> Supervisor 'Elixir.DomoapiUserWeb.Endpoint' had child {ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'} started with 'Elixir.Phoenix.Endpoint.Cowboy2Adapter':start_link(http, 'Elixir.DomoapiUserWeb.Endpoint', {ranch_listener_sup,start_link,['Elixir.DomoapiUserWeb.Endpoint.HTTP',ranch_tcp,#{max_connections => ...,...},...]}) at undefined exit with reason {shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}} in context start_error
2019-11-17 19:34:54.251 [error] <0.498.0> Supervisor 'Elixir.DomoapiUser.Supervisor' had child 'Elixir.DomoapiUserWeb.Endpoint' started with 'Elixir.DomoapiUserWeb.Endpoint':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}} in context start_error
2019-11-17 19:34:54.251 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DomoapiUserWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}}}},{'Elixir.DomoapiUser.Application',start,[normal,[]]}} in application_master:init/4 line 138
2019-11-17 19:37:38.002 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:37:38.013 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:37:38.019 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:37:38.029 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:37:38.032 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:37:38.033 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:37:38.044 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:37:38.044 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:37:38.052 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:37:38.057 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:37:38.060 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:37:38.067 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:37:38.082 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:37:38.083 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:37:38.085 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:37:38.086 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:37:38.089 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:37:38.146 [error] <0.520.0> Failed to start Ranch listener 'Elixir.DomoapiUserWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,9080}]) for reason eaddrinuse (address already in use)
2019-11-17 19:37:38.172 [error] <0.518.0> Supervisor {<0.518.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.DomoapiUserWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2019-11-17 19:37:38.172 [error] <0.520.0> CRASH REPORT Process <0.520.0> with 0 neighbours exited with reason: {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2019-11-17 19:37:38.172 [error] <0.499.0> Supervisor 'Elixir.DomoapiUserWeb.Endpoint' had child {ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'} started with 'Elixir.Phoenix.Endpoint.Cowboy2Adapter':start_link(http, 'Elixir.DomoapiUserWeb.Endpoint', {ranch_listener_sup,start_link,['Elixir.DomoapiUserWeb.Endpoint.HTTP',ranch_tcp,#{max_connections => ...,...},...]}) at undefined exit with reason {shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}} in context start_error
2019-11-17 19:37:38.172 [error] <0.498.0> Supervisor 'Elixir.DomoapiUser.Supervisor' had child 'Elixir.DomoapiUserWeb.Endpoint' started with 'Elixir.DomoapiUserWeb.Endpoint':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}} in context start_error
2019-11-17 19:37:38.172 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DomoapiUserWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}}}},{'Elixir.DomoapiUser.Application',start,[normal,[]]}} in application_master:init/4 line 138
2019-11-17 19:38:40.057 [info] <0.59.0> SIGTERM received - shutting down
2019-11-17 19:38:44.448 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:38:44.458 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:38:44.464 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:38:44.474 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:38:44.478 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:38:44.478 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:38:44.489 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:38:44.489 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:38:44.496 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:38:44.501 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:38:44.503 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:38:44.510 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:38:44.524 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:38:44.526 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:38:44.527 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:38:44.528 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:38:44.531 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:38:45.000 [warning] <0.445.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:39:41.884 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:39:41.894 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:39:41.900 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:39:41.910 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:39:41.914 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:39:41.914 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:39:41.925 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:39:41.926 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:39:41.933 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:39:41.938 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:39:41.941 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:39:41.948 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:39:41.963 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:39:41.965 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:39:41.966 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:39:41.968 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:39:41.971 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:39:43.000 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:40:27.700 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.700 [error] <0.1347.0> CRASH REPORT Process <0.1347.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.700 [error] <0.1346.0> CRASH REPORT Process <0.1346.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.701 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.749 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1343.0>,1,<0.1344.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:44:43.277 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:44:43.288 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:44:43.294 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:44:43.303 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:44:43.308 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:44:43.308 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:44:43.318 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:44:43.318 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:44:43.325 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:44:43.330 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:44:43.332 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:44:43.339 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:44:43.353 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:44:43.354 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:44:43.356 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:44:43.357 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:44:43.360 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:44:44.000 [warning] <0.454.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:45:08.035 [error] <0.1333.0> CRASH REPORT Process <0.1333.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.035 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.037 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.037 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.076 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1341.0>,1,<0.1342.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:47:48.257 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:47:48.269 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:47:48.276 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:47:48.288 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:47:48.292 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:47:48.292 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:47:48.303 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:47:48.303 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:47:48.312 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:47:48.318 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:47:48.321 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:47:48.328 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:47:48.343 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:47:48.344 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:47:48.346 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:47:48.347 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:47:48.350 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:47:49.000 [warning] <0.454.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:47:59.699 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.700 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.701 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.701 [error] <0.1345.0> CRASH REPORT Process <0.1345.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.748 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1339.0>,1,<0.1340.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:50:15.784 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:50:15.796 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:50:15.802 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:50:15.813 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:50:15.818 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:50:15.818 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:50:15.830 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:50:15.830 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:50:15.837 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:50:15.844 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:50:15.846 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:50:15.852 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:50:15.867 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:50:15.869 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:50:15.870 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:50:15.872 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:50:15.875 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:50:15.999 [warning] <0.454.0> lager_error_logger_h dropped 466 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:50:16.001 [info] <0.43.0> Application gen_stage started on node nonode@nohost
2019-11-17 19:50:16.004 [info] <0.43.0> Application crontab started on node nonode@nohost
2019-11-17 19:50:16.015 [info] <0.43.0> Application gen_state_machine started on node nonode@nohost
2019-11-17 19:50:16.023 [info] <0.43.0> Application libring started on node nonode@nohost
2019-11-17 19:50:16.054 [info] <0.43.0> Application swarm started on node nonode@nohost
2019-11-17 19:50:16.063 [info] <0.43.0> Application quantum started on node nonode@nohost
2019-11-17 19:50:17.000 [warning] <0.454.0> lager_error_logger_h dropped 226 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:50:31.865 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.865 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.866 [error] <0.1333.0> CRASH REPORT Process <0.1333.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.873 [error] <0.1347.0> CRASH REPORT Process <0.1347.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.914 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1342.0>,1,<0.1343.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:52:01.442 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:52:01.453 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:52:01.460 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:52:01.472 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:52:01.477 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:52:01.477 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:52:01.489 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:52:01.489 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:52:01.497 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:52:01.503 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:52:01.505 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:52:01.512 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:52:01.527 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:52:01.529 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:52:01.530 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:52:01.531 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:52:01.534 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:52:01.999 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:52:10.285 [error] <0.1335.0> CRASH REPORT Process <0.1335.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.286 [error] <0.1345.0> CRASH REPORT Process <0.1345.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.286 [error] <0.1347.0> CRASH REPORT Process <0.1347.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.286 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.334 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1346.0>,1,<0.1347.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:55:29.549 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:55:29.559 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:55:29.565 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:55:29.575 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:55:29.579 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:55:29.579 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:55:29.590 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:55:29.590 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:55:29.598 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:55:29.603 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:55:29.606 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:55:29.613 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:55:29.627 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:55:29.629 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:55:29.631 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:55:29.632 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:55:29.635 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:55:29.999 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:55:39.618 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.619 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.619 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.619 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.662 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1331.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:57:45.000 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 19:57:45.013 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 19:57:45.020 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 19:57:45.032 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 19:57:45.037 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 19:57:45.037 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 19:57:45.048 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 19:57:45.048 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 19:57:45.057 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 19:57:45.063 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 19:57:45.066 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 19:57:45.073 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 19:57:45.088 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 19:57:45.090 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 19:57:45.091 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 19:57:45.092 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 19:57:45.095 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 19:57:45.999 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 19:58:03.992 [error] <0.1338.0> CRASH REPORT Process <0.1338.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 234,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:03.992 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:03.993 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:03.994 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:04.035 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1331.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:01:04.486 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 20:01:04.497 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 20:01:04.503 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 20:01:04.514 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 20:01:04.518 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 20:01:04.518 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 20:01:04.530 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 20:01:04.530 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 20:01:04.538 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 20:01:04.543 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 20:01:04.545 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 20:01:04.552 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 20:01:04.566 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 20:01:04.567 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 20:01:04.569 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 20:01:04.570 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 20:01:04.573 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 20:01:05.000 [warning] <0.453.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 20:01:14.656 [error] <0.1346.0> CRASH REPORT Process <0.1346.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:01:14.685 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1345.0>,1,<0.1346.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:02:37.589 [error] <0.1396.0> CRASH REPORT Process <0.1396.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:02:37.599 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1395.0>,1,<0.1396.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:03:27.110 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 20:03:27.122 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 20:03:27.130 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 20:03:27.142 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 20:03:27.147 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 20:03:27.147 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 20:03:27.159 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 20:03:27.159 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 20:03:27.167 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 20:03:27.172 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 20:03:27.175 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 20:03:27.181 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 20:03:27.198 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 20:03:27.200 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 20:03:27.202 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 20:03:27.203 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 20:03:27.206 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 20:03:28.000 [warning] <0.445.0> lager_error_logger_h dropped 741 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 20:03:44.345 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.345 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.346 [error] <0.1337.0> CRASH REPORT Process <0.1337.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 234,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.347 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.392 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1330.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:14:31.584 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-17 20:14:31.594 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-17 20:14:31.600 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-17 20:14:31.611 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-17 20:14:31.615 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-17 20:14:31.616 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-17 20:14:31.627 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-17 20:14:31.628 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-17 20:14:31.635 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-17 20:14:31.641 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-17 20:14:31.643 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-17 20:14:31.651 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-11-17 20:14:31.665 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-11-17 20:14:31.667 [info] <0.43.0> Application phoenix_swagger started on node nonode@nohost
2019-11-17 20:14:31.668 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-11-17 20:14:31.669 [info] <0.43.0> Application corsica started on node nonode@nohost
2019-11-17 20:14:31.673 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-11-17 20:14:31.999 [warning] <0.445.0> lager_error_logger_h dropped 615 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-17 20:14:32.005 [info] <0.43.0> Application uuid started on node nonode@nohost
2019-11-17 20:14:32.027 [info] <0.43.0> Application poison started on node nonode@nohost
2019-11-17 20:14:32.032 [info] <0.43.0> Application joken started on node nonode@nohost
2019-11-17 20:14:32.058 [info] <0.43.0> Application pigeon started on node nonode@nohost
2019-11-17 20:14:33.000 [warning] <0.445.0> lager_error_logger_h dropped 77 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-18 00:00:00.005 [error] <0.1435.0> ** Task <0.1435.0> terminating
** Started from <0.1434.0>
** When function  == #Fun<Elixir.Quantum.Executor.7.12665260>
**      arguments == []
** Reason for termination == 
** {function_clause,[{'Elixir.IO',chardata_to_string,[nil],[{file,"lib/io.ex"},{line,557}]},{'Elixir.File',ls,1,[{file,"lib/file.ex"},{line,1556}]},{'Elixir.Archive.CheckFile',check_dir,0,[{file,"lib/archive/check_file.ex"},{line,8}]},{'Elixir.Quantum.Executor','-run/4-fun-3-',3,[{file,"lib/quantum/executor.ex"},{line,141}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{'Elixir.Task.Supervised',reply,5,[{file,"lib/task/supervised.ex"},{line,35}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-18 00:00:00.026 [error] <0.1435.0>@Elixir.IO:chardata_to_string:557 CRASH REPORT Process <0.1435.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':chardata_to_string(nil) line 557
2019-11-18 00:00:00.026 [error] <0.1150.0>@Elixir.IO:chardata_to_string:557 Supervisor 'Elixir.Archive.Scheduler.Task.Supervisor' had child undefined started with {'Elixir.Task.Supervised',start_link,undefined} at <0.1435.0> exit with reason no function clause matching 'Elixir.IO':chardata_to_string(nil) line 557 in context child_terminated
